theme: jekyll-theme-minimal
home_title: Air Workflows
title: Turn Your Business Into An Idea Workflow
description: Air Workflows is fast and flexible way to turn your business into an idea workflow to keep track of anything.
logo: /assets/airworkflows-logo.png
github.owner_url: https://github.com/airworkflows
github.owner_name: Air Workflows
